[programs.devnet]
anchor_escrow = "FBqs6w6dNmKCvL2J55K8VKP1CNV7vKfUYyLskhZfaWas"

[registry]
url = "https://anchor.projectserum.com"

[provider]
wallet = "~/.config/solana/id.json"
cluster="localnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
